require './lib/parse_data'
require 'nokogiri'
require 'gem_menu'
require './lib/weatherCLI/version'
require './lib/forecast'
require './lib/weathercard'
require 'json'
require './lib/concerns/mass_initialize'

TEST_PATH = './fixtures/weather.html'
